# Generated by Django 5.1.5 on 2026-09-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_kyte',
        ),
    ]
