# Generated by Django 5.1.5 on 2026-09-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_backfill_group_chat_schema'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='msg_recv_time_idx',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='encrypted_symmetric_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_encrypted_symmetric_key',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
        ),
    ]
