# Generated by Django 5.1.5 on 2026-09-17 05:16

from django.db import migrations


def wipe_messages_predating_the_chain(apps, schema_editor):
    # Existing rows have no real seq/prev_hash history (there's nothing to
    # backfill them from -- the chain requires having been maintained from
    # message 0), and a chat with more than one existing message would
    # collide on the seq=0 default under the next migration's
    # unique_together constraint. Same single-cutover precedent as 0015:
    # there's no real production user base to preserve continuity for, and
    # message history is already ephemeral by design (cleared whenever a
    # chat fully empties).
    #
    # Split into its own migration (rather than combined with the schema
    # change in 0019) because Postgres won't allow ALTER TABLE on a table
    # with pending trigger events from a cascading DELETE in the same
    # transaction ("cannot ALTER TABLE ... because it has pending trigger
    # events") -- each migration file commits separately.
    Message = apps.get_model("chat", "Message")
    Message.objects.all().delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_accountless_chat_identity'),
    ]

    operations = [
        migrations.RunPython(wipe_messages_predating_the_chain, noop_reverse),
    ]
