# Generated by Django 5.1.5 on 2026-09-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_message_prev_hash_message_seq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='prev_hash',
            field=models.CharField(default='0' * 64, max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='seq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('chat', 'seq')},
        ),
    ]
