# Generated by Django 5.1.5 on 2026-09-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_message_chain_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_active',
        ),
    ]
