# Generated by Django 5.1.5 on 2026-09-17 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_wipe_messages_predating_forward_secrecy'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_chain_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChainKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_keys', to='chat.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_chain_keys', to='chat.chatparticipant')),
            ],
            options={
                'unique_together': {('sender', 'epoch')},
            },
        ),
        migrations.CreateModel(
            name='ChainKeyWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_seed', models.TextField()),
                ('chain_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wraps', to='chat.chainkey')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_key_wraps', to='chat.chatparticipant')),
            ],
            options={
                'unique_together': {('chain_key', 'recipient')},
            },
        ),
    ]
