# Generated by Django 5.1.5 on 2026-09-18 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_message_sender_chain_epoch_chainkey_chainkeywrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
