# Generated by Django 5.1.5 on 2026-09-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_chatparticipant_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='signature',
            new_name='mac',
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='signing_public_key',
        ),
    ]
