# Generated by Django 5.1.5 on 2026-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_message_expiry_and_read_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chain_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
