# Generated by Django 5.1.5 on 2026-09-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_message_chain_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageKey',
        ),
    ]
