# Generated by Django 5.1.5 on 2026-09-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_chat_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='pin',
        ),
        migrations.CreateModel(
            name='ChatInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=6)),
                ('code_hmac', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('open', 'open'), ('consumed', 'consumed'), ('burned', 'burned'), ('revoked', 'revoked')], default='open', max_length=8)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.chat')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_issued', to='chat.chatparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'open')), fields=('handle',), name='unique_open_invite_handle')],
            },
        ),
    ]
